name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.0.3
      with:
        # The Julia version to download (if necessary) and use. Example: 1.0.4
        version: 1.3
        # Architecture of the Julia binaries. Defaults to x64.
        arch: x64
    - name: build-and-deploy
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        julia -e 'import Pkg;Pkg.add("Documenter")'
        cd docs
        julia --color=yes make.jl
